title: Denton's Blog
description: A cybersecurity and tech focused blog from a college student
theme: jekyll-theme-slate

plugins:
  - jekyll-include-cache

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

nav:
  - title: Home
    url: /
  - title: Writeups
    url: /writeups.html
  - title: Events
    url: /events.html
  - title: Projects
    url: /projects.html
  - title: All Posts
    url: /all-posts.html
  - title: Tags
    url: /tags/
  - title: About
    url: /about
    
sass:
  style: compressed
