title: Denton's Blog
description: Cybersecurity and tech from a college student
theme: jekyll-theme-slate

nav:
  - title: Home
    url: /
  - title: Writeups
    url: /writeups.html
  - title: Events
    url: /events.html
  - title: Projects
    url: /projects.html
  - title: About
    url: /about.html
    
sass:
  style: compressed
